version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - /server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./server
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: always
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata: